# Generated by Django 5.0.3 on 2024-03-29 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landfill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operational_timespan', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='STS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.IntegerField(unique=True)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Open Truck', 'Open Truck'), ('Dump Truck', 'Dump Truck'), ('Compactor', 'Compactor'), ('Container Carrier', 'Container Carrier')], max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_cost_loaded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_cost_unloaded', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FuelSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_of_waste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_of_arrival', models.DateTimeField()),
                ('time_of_departure', models.DateTimeField()),
                ('landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landfill')),
                ('sts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sts')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
    ]
