# Generated by Django 5.0.3 on 2024-03-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('System Admin', 'System Admin'), ('STS Manager', 'STS Manager'), ('Landfill Manager', 'Landfill Manager'), ('Unassigned', 'Unassigned')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
